// VOCABULARY DATA - CHUNK 1 (Words 1-100)
// Copy and paste this into your vocabulary array
const vocabulary = [
{ word: 'the', translation: 'определителен член', level: 1, category: 'grammar' },
{ word: 'be', translation: 'съм, бъда', level: 1, category: 'verb' },
{ word: 'and', translation: 'и', level: 1, category: 'grammar' },
{ word: 'of', translation: 'от, на', level: 1, category: 'grammar' },
{ word: 'a', translation: 'един, една, едно', level: 1, category: 'grammar' },
{ word: 'to', translation: 'към, до', level: 1, category: 'grammar' },
{ word: 'in', translation: 'в, във', level: 1, category: 'grammar' },
{ word: 'have', translation: 'имам', level: 1, category: 'verb' },
{ word: 'I', translation: 'аз', level: 1, category: 'pronoun' },
{ word: 'it', translation: 'то', level: 1, category: 'pronoun' },
{ word: 'for', translation: 'за', level: 1, category: 'grammar' },
{ word: 'not', translation: 'не', level: 1, category: 'grammar' },
{ word: 'on', translation: 'на, върху', level: 1, category: 'grammar' },
{ word: 'with', translation: 'с, със', level: 1, category: 'grammar' },
{ word: 'he', translation: 'той', level: 1, category: 'pronoun' },
{ word: 'as', translation: 'като, като че', level: 1, category: 'grammar' },
{ word: 'you', translation: 'ти, вие', level: 1, category: 'pronoun' },
{ word: 'do', translation: 'правя', level: 1, category: 'verb' },
{ word: 'at', translation: 'на, в', level: 1, category: 'grammar' },
{ word: 'this', translation: 'този, това', level: 1, category: 'pronoun' },
{ word: 'but', translation: 'но', level: 1, category: 'grammar' },
{ word: 'his', translation: 'негов', level: 1, category: 'pronoun' },
{ word: 'by', translation: 'от, при', level: 1, category: 'grammar' },
{ word: 'from', translation: 'от', level: 1, category: 'grammar' },
{ word: 'they', translation: 'те', level: 1, category: 'pronoun' },
{ word: 'we', translation: 'ние', level: 1, category: 'pronoun' },
{ word: 'say', translation: 'казвам', level: 1, category: 'verb' },
{ word: 'her', translation: 'нейн, я', level: 1, category: 'pronoun' },
{ word: 'she', translation: 'тя', level: 1, category: 'pronoun' },
{ word: 'or', translation: 'или', level: 1, category: 'grammar' },
{ word: 'an', translation: 'един (пред гласна)', level: 1, category: 'grammar' },
{ word: 'will', translation: 'ще', level: 1, category: 'verb' },
{ word: 'my', translation: 'мой', level: 1, category: 'pronoun' },
{ word: 'one', translation: 'един', level: 1, category: 'number' },
{ word: 'all', translation: 'всички', level: 1, category: 'pronoun' },
{ word: 'would', translation: 'бих, би', level: 1, category: 'verb' },
{ word: 'there', translation: 'там', level: 1, category: 'adverb' },
{ word: 'their', translation: 'техен', level: 1, category: 'pronoun' },
{ word: 'what', translation: 'какво', level: 1, category: 'pronoun' },
{ word: 'so', translation: 'така, толкова', level: 1, category: 'adverb' },
{ word: 'up', translation: 'нагоре', level: 1, category: 'adverb' },
{ word: 'out', translation: 'навън', level: 1, category: 'adverb' },
{ word: 'if', translation: 'ако', level: 1, category: 'grammar' },
{ word: 'about', translation: 'за, относно', level: 1, category: 'grammar' },
{ word: 'who', translation: 'кой', level: 1, category: 'pronoun' },
{ word: 'get', translation: 'получавам', level: 1, category: 'verb' },
{ word: 'which', translation: 'който, кой', level: 1, category: 'pronoun' },
{ word: 'go', translation: 'отивам', level: 1, category: 'verb' },
{ word: 'me', translation: 'мен, ми', level: 1, category: 'pronoun' },
{ word: 'when', translation: 'кога', level: 1, category: 'adverb' },
{ word: 'make', translation: 'правя', level: 1, category: 'verb' },
{ word: 'can', translation: 'мога', level: 1, category: 'verb' },
{ word: 'like', translation: 'харесвам', level: 1, category: 'verb' },
{ word: 'time', translation: 'време', level: 1, category: 'noun' },
{ word: 'no', translation: 'не, няма', level: 1, category: 'adverb' },
{ word: 'just', translation: 'само, просто', level: 1, category: 'adverb' },
{ word: 'him', translation: 'него, му', level: 1, category: 'pronoun' },
{ word: 'know', translation: 'знам', level: 1, category: 'verb' },
{ word: 'take', translation: 'взимам', level: 1, category: 'verb' },
{ word: 'people', translation: 'хора', level: 1, category: 'noun' },
{ word: 'into', translation: 'в, вътре в', level: 1, category: 'grammar' },
{ word: 'year', translation: 'година', level: 1, category: 'noun' },
{ word: 'your', translation: 'твой', level: 1, category: 'pronoun' },
{ word: 'good', translation: 'добър', level: 1, category: 'adjective' },
{ word: 'some', translation: 'някои, малко', level: 1, category: 'pronoun' },
{ word: 'could', translation: 'можех, можеше', level: 1, category: 'verb' },
{ word: 'them', translation: 'тях, им', level: 1, category: 'pronoun' },
{ word: 'see', translation: 'виждам', level: 1, category: 'verb' },
{ word: 'other', translation: 'друг', level: 1, category: 'adjective' },
{ word: 'than', translation: 'от, отколкото', level: 1, category: 'grammar' },
{ word: 'then', translation: 'тогава', level: 1, category: 'adverb' },
{ word: 'now', translation: 'сега', level: 1, category: 'adverb' },
{ word: 'look', translation: 'гледам', level: 1, category: 'verb' },
{ word: 'only', translation: 'само', level: 1, category: 'adverb' },
{ word: 'come', translation: 'идвам', level: 1, category: 'verb' },
{ word: 'its', translation: 'негов (на него)', level: 1, category: 'pronoun' },
{ word: 'over', translation: 'над, през', level: 1, category: 'grammar' },
{ word: 'think', translation: 'мисля', level: 1, category: 'verb' },
{ word: 'also', translation: 'също', level: 1, category: 'adverb' },
{ word: 'back', translation: 'назад', level: 1, category: 'adverb' },
{ word: 'after', translation: 'след', level: 1, category: 'grammar' },
{ word: 'use', translation: 'използвам', level: 1, category: 'verb' },
{ word: 'two', translation: 'две', level: 1, category: 'number' },
{ word: 'how', translation: 'как', level: 1, category: 'adverb' },
{ word: 'our', translation: 'наш', level: 1, category: 'pronoun' },
{ word: 'work', translation: 'работа, работя', level: 1, category: 'noun' },
{ word: 'first', translation: 'първи', level: 1, category: 'adjective' },
{ word: 'well', translation: 'добре', level: 1, category: 'adverb' },
{ word: 'way', translation: 'път, начин', level: 1, category: 'noun' },
{ word: 'even', translation: 'дори', level: 1, category: 'adverb' },
{ word: 'new', translation: 'нов', level: 1, category: 'adjective' },
{ word: 'want', translation: 'искам', level: 1, category: 'verb' },
{ word: 'because', translation: 'защото', level: 1, category: 'grammar' },
{ word: 'any', translation: 'някой, който и да е', level: 1, category: 'pronoun' },
{ word: 'these', translation: 'тези', level: 1, category: 'pronoun' },
{ word: 'give', translation: 'давам', level: 1, category: 'verb' },
{ word: 'day', translation: 'ден', level: 1, category: 'noun' },
{ word: 'most', translation: 'най-много', level: 1, category: 'adverb' },
{ word: 'us', translation: 'нас, ни', level: 1, category: 'pronoun' },
    { word: 'find', translation: 'намирам', level: 1, category: 'verb' },
    { word: 'tell', translation: 'казвам, разказвам', level: 1, category: 'verb' },
    { word: 'ask', translation: 'питам', level: 1, category: 'verb' },
    { word: 'try', translation: 'опитвам', level: 1, category: 'verb' },
    { word: 'call', translation: 'обаждам се', level: 1, category: 'verb' },
    { word: 'need', translation: 'нуждая се', level: 1, category: 'verb' },
    { word: 'feel', translation: 'чувствам', level: 1, category: 'verb' },
    { word: 'become', translation: 'ставам', level: 1, category: 'verb' },
    { word: 'leave', translation: 'напускам', level: 1, category: 'verb' },
    { word: 'put', translation: 'слагам', level: 1, category: 'verb' },
    { word: 'mean', translation: 'означавам', level: 1, category: 'verb' },
    { word: 'keep', translation: 'пазя', level: 1, category: 'verb' },
    { word: 'let', translation: 'позволявам', level: 1, category: 'verb' },
    { word: 'begin', translation: 'започвам', level: 1, category: 'verb' },
    { word: 'seem', translation: 'изглеждам', level: 1, category: 'verb' },
    { word: 'help', translation: 'помагам', level: 1, category: 'verb' },
    { word: 'show', translation: 'показвам', level: 1, category: 'verb' },
    { word: 'hear', translation: 'чувам', level: 1, category: 'verb' },
    { word: 'play', translation: 'играя', level: 1, category: 'verb' },
    { word: 'run', translation: 'бягам', level: 1, category: 'verb' },
    { word: 'move', translation: 'движа се', level: 1, category: 'verb' },
    { word: 'live', translation: 'живея', level: 1, category: 'verb' },
    { word: 'believe', translation: 'вярвам', level: 1, category: 'verb' },
    { word: 'bring', translation: 'донасям', level: 1, category: 'verb' },
    { word: 'happen', translation: 'случвам се', level: 1, category: 'verb' },
    { word: 'write', translation: 'пиша', level: 1, category: 'verb' },
    { word: 'sit', translation: 'сядам', level: 1, category: 'verb' },
    { word: 'stand', translation: 'стоя', level: 1, category: 'verb' },
    { word: 'lose', translation: 'губя', level: 1, category: 'verb' },
    { word: 'pay', translation: 'плащам', level: 1, category: 'verb' },
    { word: 'meet', translation: 'срещам', level: 1, category: 'verb' },
    { word: 'include', translation: 'включвам', level: 1, category: 'verb' },
    { word: 'continue', translation: 'продължавам', level: 1, category: 'verb' },
    { word: 'set', translation: 'поставям', level: 1, category: 'verb' },
    { word: 'learn', translation: 'уча', level: 1, category: 'verb' },
    { word: 'change', translation: 'променям', level: 1, category: 'verb' },
    { word: 'lead', translation: 'водя', level: 1, category: 'verb' },
    { word: 'understand', translation: 'разбирам', level: 1, category: 'verb' },
    { word: 'watch', translation: 'гледам', level: 1, category: 'verb' },
    { word: 'follow', translation: 'следвам', level: 1, category: 'verb' },
    { word: 'stop', translation: 'спирам', level: 1, category: 'verb' },
    { word: 'create', translation: 'създавам', level: 1, category: 'verb' },
    { word: 'speak', translation: 'говоря', level: 1, category: 'verb' },
    { word: 'read', translation: 'чета', level: 1, category: 'verb' },
    { word: 'spend', translation: 'харча, прекарвам', level: 1, category: 'verb' },
    { word: 'grow', translation: 'раста', level: 1, category: 'verb' },
    { word: 'open', translation: 'отварям', level: 1, category: 'verb' },
    { word: 'walk', translation: 'ходя', level: 1, category: 'verb' },
    { word: 'win', translation: 'печеля', level: 1, category: 'verb' },
    { word: 'teach', translation: 'преподавам', level: 1, category: 'verb' },
    { word: 'offer', translation: 'предлагам', level: 1, category: 'verb' },
    { word: 'remember', translation: 'помня', level: 1, category: 'verb' },
    { word: 'love', translation: 'обичам', level: 1, category: 'verb' },
    { word: 'consider', translation: 'обмислям', level: 1, category: 'verb' },
    { word: 'appear', translation: 'появявам се', level: 1, category: 'verb' },
    { word: 'buy', translation: 'купувам', level: 1, category: 'verb' },
    { word: 'serve', translation: 'обслужвам', level: 1, category: 'verb' },
    { word: 'die', translation: 'умирам', level: 1, category: 'verb' },
    { word: 'send', translation: 'изпращам', level: 1, category: 'verb' },
    { word: 'build', translation: 'строя', level: 1, category: 'verb' },
    { word: 'stay', translation: 'оставам', level: 1, category: 'verb' },
    { word: 'fall', translation: 'падам', level: 1, category: 'verb' },
    { word: 'cut', translation: 'режа', level: 1, category: 'verb' },
    { word: 'reach', translation: 'достигам', level: 1, category: 'verb' },
    { word: 'kill', translation: 'убивам', level: 1, category: 'verb' },
    { word: 'raise', translation: 'вдигам', level: 1, category: 'verb' },
    { word: 'pass', translation: 'минавам', level: 1, category: 'verb' },
    { word: 'sell', translation: 'продавам', level: 1, category: 'verb' },
    { word: 'require', translation: 'изисквам', level: 1, category: 'verb' },
    { word: 'decide', translation: 'решавам', level: 1, category: 'verb' },
    { word: 'return', translation: 'връщам се', level: 1, category: 'verb' },
    { word: 'explain', translation: 'обяснявам', level: 1, category: 'verb' },
    { word: 'hope', translation: 'надявам се', level: 1, category: 'verb' },
    { word: 'develop', translation: 'развивам', level: 1, category: 'verb' },
    { word: 'carry', translation: 'нося', level: 1, category: 'verb' },
    { word: 'break', translation: 'чупя', level: 1, category: 'verb' },
    { word: 'receive', translation: 'получавам', level: 1, category: 'verb' },
    { word: 'agree', translation: 'съгласявам се', level: 1, category: 'verb' },
    { word: 'support', translation: 'подкрепям', level: 1, category: 'verb' },
    { word: 'hit', translation: 'удрям', level: 1, category: 'verb' },
    { word: 'produce', translation: 'произвеждам', level: 1, category: 'verb' },
    { word: 'eat', translation: 'ям', level: 1, category: 'verb' },
    { word: 'cover', translation: 'покривам', level: 1, category: 'verb' },
    { word: 'catch', translation: 'хващам', level: 1, category: 'verb' },
    { word: 'draw', translation: 'рисувам', level: 1, category: 'verb' },
    { word: 'choose', translation: 'избирам', level: 1, category: 'verb' },
    { word: 'sleep', translation: 'спя', level: 1, category: 'verb' },
    { word: 'wear', translation: 'нося (дреха)', level: 1, category: 'verb' },
    { word: 'drink', translation: 'пия', level: 1, category: 'verb' },
    { word: 'drive', translation: 'карам (кола)', level: 1, category: 'verb' },
    { word: 'sing', translation: 'пея', level: 1, category: 'verb' },
    { word: 'swim', translation: 'плувам', level: 1, category: 'verb' },
    { word: 'fly', translation: 'летя', level: 1, category: 'verb' },
    { word: 'dance', translation: 'танцувам', level: 1, category: 'verb' },
    { word: 'cook', translation: 'готвя', level: 1, category: 'verb' },
    { word: 'clean', translation: 'чистя', level: 1, category: 'verb' },
    { word: 'wash', translation: 'мия', level: 1, category: 'verb' },
    { word: 'cry', translation: 'плача', level: 1, category: 'verb' },
    { word: 'laugh', translation: 'смея се', level: 1, category: 'verb' },
    // VOCABULARY DATA - CHUNK 3 (Words 201-300)
// Copy and paste this into your vocabulary array

    { word: 'man', translation: 'мъж', level: 1, category: 'noun' },
    { word: 'woman', translation: 'жена', level: 1, category: 'noun' },
    { word: 'child', translation: 'дете', level: 1, category: 'noun' },
    { word: 'boy', translation: 'момче', level: 1, category: 'noun' },
    { word: 'girl', translation: 'момиче', level: 1, category: 'noun' },
    { word: 'mother', translation: 'майка', level: 1, category: 'noun' },
    { word: 'father', translation: 'баща', level: 1, category: 'noun' },
    { word: 'friend', translation: 'приятел', level: 1, category: 'noun' },
    { word: 'family', translation: 'семейство', level: 1, category: 'noun' },
    { word: 'house', translation: 'къща', level: 1, category: 'noun' },
    { word: 'home', translation: 'дом', level: 1, category: 'noun' },
    { word: 'school', translation: 'училище', level: 1, category: 'noun' },
    { word: 'room', translation: 'стая', level: 1, category: 'noun' },
    { word: 'door', translation: 'врата', level: 1, category: 'noun' },
    { word: 'window', translation: 'прозорец', level: 1, category: 'noun' },
    { word: 'table', translation: 'маса', level: 1, category: 'noun' },
    { word: 'chair', translation: 'стол', level: 1, category: 'noun' },
    { word: 'bed', translation: 'легло', level: 1, category: 'noun' },
    { word: 'book', translation: 'книга', level: 1, category: 'noun' },
    { word: 'phone', translation: 'телефон', level: 1, category: 'noun' },
    { word: 'car', translation: 'кола', level: 1, category: 'noun' },
    { word: 'water', translation: 'вода', level: 1, category: 'noun' },
    { word: 'food', translation: 'храна', level: 1, category: 'noun' },
    { word: 'hand', translation: 'ръка', level: 1, category: 'noun' },
    { word: 'head', translation: 'глава', level: 1, category: 'noun' },
    { word: 'eye', translation: 'око', level: 1, category: 'noun' },
    { word: 'ear', translation: 'ухо', level: 1, category: 'noun' },
    { word: 'nose', translation: 'нос', level: 1, category: 'noun' },
    { word: 'mouth', translation: 'уста', level: 1, category: 'noun' },
    { word: 'face', translation: 'лице', level: 1, category: 'noun' },
    { word: 'hair', translation: 'коса', level: 1, category: 'noun' },
    { word: 'body', translation: 'тяло', level: 1, category: 'noun' },
    { word: 'foot', translation: 'крак (стъпало)', level: 1, category: 'noun' },
    { word: 'leg', translation: 'крак', level: 1, category: 'noun' },
    { word: 'arm', translation: 'ръка (цялата)', level: 1, category: 'noun' },
    { word: 'finger', translation: 'пръст (на ръка)', level: 1, category: 'noun' },
    { word: 'today', translation: 'днес', level: 1, category: 'noun' },
    { word: 'tomorrow', translation: 'утре', level: 1, category: 'noun' },
    { word: 'yesterday', translation: 'вчера', level: 1, category: 'noun' },
    { word: 'morning', translation: 'сутрин', level: 1, category: 'noun' },
    { word: 'afternoon', translation: 'следобед', level: 1, category: 'noun' },
    { word: 'evening', translation: 'вечер', level: 1, category: 'noun' },
    { word: 'night', translation: 'нощ', level: 1, category: 'noun' },
    { word: 'week', translation: 'седмица', level: 1, category: 'noun' },
    { word: 'month', translation: 'месец', level: 1, category: 'noun' },
    { word: 'world', translation: 'свят', level: 1, category: 'noun' },
    { word: 'country', translation: 'страна', level: 1, category: 'noun' },
    { word: 'city', translation: 'град', level: 1, category: 'noun' },
    { word: 'town', translation: 'град (малък)', level: 1, category: 'noun' },
    { word: 'street', translation: 'улица', level: 1, category: 'noun' },
    { word: 'place', translation: 'място', level: 1, category: 'noun' },
    { word: 'thing', translation: 'нещо', level: 1, category: 'noun' },
    { word: 'life', translation: 'живот', level: 1, category: 'noun' },
    { word: 'part', translation: 'част', level: 1, category: 'noun' },
    { word: 'side', translation: 'страна', level: 1, category: 'noun' },
    { word: 'point', translation: 'точка', level: 1, category: 'noun' },
    { word: 'end', translation: 'край', level: 1, category: 'noun' },
    { word: 'number', translation: 'число', level: 1, category: 'noun' },
    { word: 'name', translation: 'име', level: 1, category: 'noun' },
    { word: 'question', translation: 'въпрос', level: 1, category: 'noun' },
    { word: 'answer', translation: 'отговор', level: 1, category: 'noun' },
    { word: 'idea', translation: 'идея', level: 1, category: 'noun' },
    { word: 'problem', translation: 'проблем', level: 1, category: 'noun' },
    { word: 'fact', translation: 'факт', level: 1, category: 'noun' },
    { word: 'case', translation: 'случай', level: 1, category: 'noun' },
    { word: 'reason', translation: 'причина', level: 1, category: 'noun' },
    { word: 'story', translation: 'история', level: 1, category: 'noun' },
    { word: 'word', translation: 'дума', level: 1, category: 'noun' },
    { word: 'money', translation: 'пари', level: 1, category: 'noun' },
    { word: 'tree', translation: 'дърво', level: 1, category: 'noun' },
    { word: 'sun', translation: 'слънце', level: 1, category: 'noun' },
    { word: 'moon', translation: 'луна', level: 1, category: 'noun' },
    { word: 'star', translation: 'звезда', level: 1, category: 'noun' },
    { word: 'dog', translation: 'куче', level: 1, category: 'noun' },
    { word: 'cat', translation: 'котка', level: 1, category: 'noun' },
    { word: 'animal', translation: 'животно', level: 1, category: 'noun' },
    { word: 'bird', translation: 'птица', level: 1, category: 'noun' },
    { word: 'fish', translation: 'риба', level: 1, category: 'noun' },
    { word: 'color', translation: 'цвят', level: 1, category: 'noun' },
    { word: 'red', translation: 'червен', level: 1, category: 'adjective' },
    { word: 'blue', translation: 'син', level: 1, category: 'adjective' },
    { word: 'green', translation: 'зелен', level: 1, category: 'adjective' },
    { word: 'yellow', translation: 'жълт', level: 1, category: 'adjective' },
    { word: 'white', translation: 'бял', level: 1, category: 'adjective' },
    { word: 'black', translation: 'черен', level: 1, category: 'adjective' },
    { word: 'orange', translation: 'оранжев', level: 1, category: 'adjective' },
    { word: 'purple', translation: 'лилав', level: 1, category: 'adjective' },
    { word: 'brown', translation: 'кафяв', level: 1, category: 'adjective' },
    { word: 'gray', translation: 'сив', level: 1, category: 'adjective' },
    { word: 'big', translation: 'голям', level: 1, category: 'adjective' },
    { word: 'small', translation: 'малък', level: 1, category: 'adjective' },
    { word: 'large', translation: 'голям (размер)', level: 1, category: 'adjective' },
    { word: 'little', translation: 'малък', level: 1, category: 'adjective' },
    { word: 'long', translation: 'дълъг', level: 1, category: 'adjective' },
    { word: 'short', translation: 'къс', level: 1, category: 'adjective' },
    { word: 'high', translation: 'висок', level: 1, category: 'adjective' },
    { word: 'low', translation: 'нисък', level: 1, category: 'adjective' },
    // VOCABULARY DATA - CHUNK 4 (Words 301-400)
// Copy and paste this into your vocabulary array

    { word: 'old', translation: 'стар', level: 1, category: 'adjective' },
    { word: 'young', translation: 'млад', level: 1, category: 'adjective' },
    { word: 'hot', translation: 'горещ', level: 1, category: 'adjective' },
    { word: 'cold', translation: 'студен', level: 1, category: 'adjective' },
    { word: 'warm', translation: 'топъл', level: 1, category: 'adjective' },
    { word: 'cool', translation: 'хладен', level: 1, category: 'adjective' },
    { word: 'fast', translation: 'бърз', level: 1, category: 'adjective' },
    { word: 'slow', translation: 'бавен', level: 1, category: 'adjective' },
    { word: 'happy', translation: 'щастлив', level: 1, category: 'adjective' },
    { word: 'sad', translation: 'тъжен', level: 1, category: 'adjective' },
    { word: 'easy', translation: 'лесен', level: 1, category: 'adjective' },
    { word: 'hard', translation: 'труден', level: 1, category: 'adjective' },
    { word: 'difficult', translation: 'труден', level: 1, category: 'adjective' },
    { word: 'early', translation: 'ранен', level: 1, category: 'adjective' },
    { word: 'late', translation: 'късен', level: 1, category: 'adjective' },
    { word: 'right', translation: 'правилен', level: 1, category: 'adjective' },
    { word: 'wrong', translation: 'грешен', level: 1, category: 'adjective' },
    { word: 'true', translation: 'истински', level: 1, category: 'adjective' },
    { word: 'false', translation: 'неверен', level: 1, category: 'adjective' },
    { word: 'nice', translation: 'хубав', level: 1, category: 'adjective' },
    { word: 'bad', translation: 'лош', level: 1, category: 'adjective' },
    { word: 'great', translation: 'страхотен', level: 1, category: 'adjective' },
    { word: 'beautiful', translation: 'красив', level: 1, category: 'adjective' },
    { word: 'ugly', translation: 'грозен', level: 1, category: 'adjective' },
    { word: 'full', translation: 'пълен', level: 1, category: 'adjective' },
    { word: 'empty', translation: 'празен', level: 1, category: 'adjective' },
    { word: 'heavy', translation: 'тежък', level: 1, category: 'adjective' },
    { word: 'light', translation: 'лек', level: 1, category: 'adjective' },
    { word: 'strong', translation: 'силен', level: 1, category: 'adjective' },
    { word: 'weak', translation: 'слаб', level: 1, category: 'adjective' },
    { word: 'three', translation: 'три', level: 1, category: 'number' },
    { word: 'four', translation: 'четири', level: 1, category: 'number' },
    { word: 'five', translation: 'пет', level: 1, category: 'number' },
    { word: 'six', translation: 'шест', level: 1, category: 'number' },
    { word: 'seven', translation: 'седем', level: 1, category: 'number' },
    { word: 'eight', translation: 'осем', level: 1, category: 'number' },
    { word: 'nine', translation: 'девет', level: 1, category: 'number' },
    { word: 'ten', translation: 'десет', level: 1, category: 'number' },
    { word: 'eleven', translation: 'единадесет', level: 1, category: 'number' },
    { word: 'twelve', translation: 'дванадесет', level: 1, category: 'number' },
    { word: 'thirteen', translation: 'тринадесет', level: 1, category: 'number' },
    { word: 'fourteen', translation: 'четиринадесет', level: 1, category: 'number' },
    { word: 'fifteen', translation: 'петнадесет', level: 1, category: 'number' },
    { word: 'twenty', translation: 'двадесет', level: 1, category: 'number' },
    { word: 'thirty', translation: 'тридесет', level: 1, category: 'number' },
    { word: 'hundred', translation: 'сто', level: 1, category: 'number' },
    { word: 'thousand', translation: 'хиляда', level: 1, category: 'number' },
    { word: 'yes', translation: 'да', level: 1, category: 'adverb' },
    { word: 'hello', translation: 'здравей', level: 1, category: 'interjection' },
    { word: 'goodbye', translation: 'довиждане', level: 1, category: 'interjection' },
    { word: 'please', translation: 'моля', level: 1, category: 'interjection' },
    { word: 'thank', translation: 'благодаря', level: 1, category: 'verb' },
    { word: 'sorry', translation: 'съжалявам', level: 1, category: 'interjection' },
    { word: 'excuse', translation: 'извинявам', level: 1, category: 'verb' },
    { word: 'here', translation: 'тук', level: 1, category: 'adverb' },
    { word: 'where', translation: 'къде', level: 1, category: 'adverb' },
    { word: 'why', translation: 'защо', level: 1, category: 'adverb' },
    { word: 'always', translation: 'винаги', level: 2, category: 'adverb' },
    { word: 'never', translation: 'никога', level: 2, category: 'adverb' },
    { word: 'often', translation: 'често', level: 2, category: 'adverb' },
    { word: 'sometimes', translation: 'понякога', level: 2, category: 'adverb' },
    { word: 'usually', translation: 'обикновено', level: 2, category: 'adverb' },
    { word: 'brother', translation: 'брат', level: 2, category: 'noun' },
    { word: 'sister', translation: 'сестра', level: 2, category: 'noun' },
    { word: 'parent', translation: 'родител', level: 2, category: 'noun' },
    { word: 'son', translation: 'син', level: 2, category: 'noun' },
    { word: 'daughter', translation: 'дъщеря', level: 2, category: 'noun' },
    { word: 'husband', translation: 'съпруг', level: 2, category: 'noun' },
    { word: 'wife', translation: 'съпруга', level: 2, category: 'noun' },
    { word: 'grandfather', translation: 'дядо', level: 2, category: 'noun' },
    { word: 'grandmother', translation: 'баба', level: 2, category: 'noun' },
    { word: 'uncle', translation: 'чичо', level: 2, category: 'noun' },
    { word: 'aunt', translation: 'леля', level: 2, category: 'noun' },
    { word: 'cousin', translation: 'братовчед', level: 2, category: 'noun' },
    { word: 'baby', translation: 'бебе', level: 2, category: 'noun' },
    { word: 'person', translation: 'човек', level: 2, category: 'noun' },
    { word: 'teacher', translation: 'учител', level: 2, category: 'noun' },
    { word: 'student', translation: 'ученик', level: 2, category: 'noun' },
    { word: 'doctor', translation: 'лекар', level: 2, category: 'noun' },
    { word: 'nurse', translation: 'медицинска сестра', level: 2, category: 'noun' },
    { word: 'police', translation: 'полиция', level: 2, category: 'noun' },
    { word: 'office', translation: 'офис', level: 2, category: 'noun' },
    { word: 'hospital', translation: 'болница', level: 2, category: 'noun' },
    { word: 'store', translation: 'магазин', level: 2, category: 'noun' },
    { word: 'market', translation: 'пазар', level: 2, category: 'noun' },
    { word: 'restaurant', translation: 'ресторант', level: 2, category: 'noun' },
    { word: 'hotel', translation: 'хотел', level: 2, category: 'noun' },
    { word: 'airport', translation: 'летище', level: 2, category: 'noun' },
    { word: 'station', translation: 'гара', level: 2, category: 'noun' },
    { word: 'bus', translation: 'автобус', level: 2, category: 'noun' },
    { word: 'train', translation: 'влак', level: 2, category: 'noun' },
    { word: 'plane', translation: 'самолет', level: 2, category: 'noun' },
    { word: 'ship', translation: 'кораб', level: 2, category: 'noun' },
    { word: 'bike', translation: 'велосипед', level: 2, category: 'noun' },
    { word: 'road', translation: 'път', level: 2, category: 'noun' },
    // VOCABULARY DATA - CHUNK 5 (Words 401-500)
// Copy and paste this into your vocabulary array

    { word: 'bridge', translation: 'мост', level: 2, category: 'noun' },
    { word: 'park', translation: 'парк', level: 2, category: 'noun' },
    { word: 'garden', translation: 'градина', level: 2, category: 'noun' },
    { word: 'forest', translation: 'гора', level: 2, category: 'noun' },
    { word: 'mountain', translation: 'планина', level: 2, category: 'noun' },
    { word: 'river', translation: 'река', level: 2, category: 'noun' },
    { word: 'sea', translation: 'море', level: 2, category: 'noun' },
    { word: 'ocean', translation: 'океан', level: 2, category: 'noun' },
    { word: 'beach', translation: 'плаж', level: 2, category: 'noun' },
    { word: 'island', translation: 'остров', level: 2, category: 'noun' },
    { word: 'lake', translation: 'езеро', level: 2, category: 'noun' },
    { word: 'farm', translation: 'ферма', level: 2, category: 'noun' },
    { word: 'field', translation: 'поле', level: 2, category: 'noun' },
    { word: 'sky', translation: 'небе', level: 2, category: 'noun' },
    { word: 'cloud', translation: 'облак', level: 2, category: 'noun' },
    { word: 'rain', translation: 'дъжд', level: 2, category: 'noun' },
    { word: 'snow', translation: 'сняг', level: 2, category: 'noun' },
    { word: 'wind', translation: 'вятър', level: 2, category: 'noun' },
    { word: 'weather', translation: 'време (метео)', level: 2, category: 'noun' },
    { word: 'season', translation: 'сезон', level: 2, category: 'noun' },
    { word: 'spring', translation: 'пролет', level: 2, category: 'noun' },
    { word: 'summer', translation: 'лято', level: 2, category: 'noun' },
    { word: 'autumn', translation: 'есен', level: 2, category: 'noun' },
    { word: 'fall', translation: 'есен', level: 2, category: 'noun' },
    { word: 'winter', translation: 'зима', level: 2, category: 'noun' },
    { word: 'breakfast', translation: 'закуска', level: 2, category: 'noun' },
    { word: 'lunch', translation: 'обяд', level: 2, category: 'noun' },
    { word: 'dinner', translation: 'вечеря', level: 2, category: 'noun' },
    { word: 'bread', translation: 'хляб', level: 2, category: 'noun' },
    { word: 'meat', translation: 'месо', level: 2, category: 'noun' },
    { word: 'chicken', translation: 'пиле', level: 2, category: 'noun' },
    { word: 'vegetable', translation: 'зеленчук', level: 2, category: 'noun' },
    { word: 'fruit', translation: 'плод', level: 2, category: 'noun' },
    { word: 'apple', translation: 'ябълка', level: 2, category: 'noun' },
    { word: 'banana', translation: 'банан', level: 2, category: 'noun' },
    { word: 'milk', translation: 'мляко', level: 2, category: 'noun' },
    { word: 'coffee', translation: 'кафе', level: 2, category: 'noun' },
    { word: 'tea', translation: 'чай', level: 2, category: 'noun' },
    { word: 'juice', translation: 'сок', level: 2, category: 'noun' },
    { word: 'egg', translation: 'яйце', level: 2, category: 'noun' },
    { word: 'cheese', translation: 'сирене', level: 2, category: 'noun' },
    { word: 'butter', translation: 'масло', level: 2, category: 'noun' },
    { word: 'sugar', translation: 'захар', level: 2, category: 'noun' },
    { word: 'salt', translation: 'сол', level: 2, category: 'noun' },
    { word: 'rice', translation: 'ориз', level: 2, category: 'noun' },
    { word: 'potato', translation: 'картоф', level: 2, category: 'noun' },
    { word: 'tomato', translation: 'домат', level: 2, category: 'noun' },
    { word: 'soup', translation: 'супа', level: 2, category: 'noun' },
    { word: 'salad', translation: 'салата', level: 2, category: 'noun' },
    { word: 'sandwich', translation: 'сандвич', level: 2, category: 'noun' },
    { word: 'pizza', translation: 'пица', level: 2, category: 'noun' },
    { word: 'cake', translation: 'торта', level: 2, category: 'noun' },
    { word: 'cookie', translation: 'бисквитка', level: 2, category: 'noun' },
    { word: 'ice cream', translation: 'сладолед', level: 2, category: 'noun' },
    { word: 'shirt', translation: 'риза', level: 2, category: 'noun' },
    { word: 'pants', translation: 'панталони', level: 2, category: 'noun' },
    { word: 'dress', translation: 'рокля', level: 2, category: 'noun' },
    { word: 'skirt', translation: 'пола', level: 2, category: 'noun' },
    { word: 'shoe', translation: 'обувка', level: 2, category: 'noun' },
    { word: 'sock', translation: 'чорап', level: 2, category: 'noun' },
    { word: 'hat', translation: 'шапка', level: 2, category: 'noun' },
    { word: 'coat', translation: 'палто', level: 2, category: 'noun' },
    { word: 'jacket', translation: 'яке', level: 2, category: 'noun' },
    { word: 'glasses', translation: 'очила', level: 2, category: 'noun' },
    { word: 'watch', translation: 'часовник', level: 2, category: 'noun' },
    { word: 'bag', translation: 'чанта', level: 2, category: 'noun' },
    { word: 'pen', translation: 'химикалка', level: 2, category: 'noun' },
    { word: 'pencil', translation: 'молив', level: 2, category: 'noun' },
    { word: 'paper', translation: 'хартия', level: 2, category: 'noun' },
    { word: 'computer', translation: 'компютър', level: 2, category: 'noun' },
    { word: 'internet', translation: 'интернет', level: 2, category: 'noun' },
    { word: 'email', translation: 'имейл', level: 2, category: 'noun' },
    { word: 'message', translation: 'съобщение', level: 2, category: 'noun' },
    { word: 'picture', translation: 'картина', level: 2, category: 'noun' },
    { word: 'photo', translation: 'снимка', level: 2, category: 'noun' },
    { word: 'camera', translation: 'камера', level: 2, category: 'noun' },
    { word: 'music', translation: 'музика', level: 2, category: 'noun' },
    { word: 'song', translation: 'песен', level: 2, category: 'noun' },
    { word: 'movie', translation: 'филм', level: 2, category: 'noun' },
    { word: 'television', translation: 'телевизия', level: 2, category: 'noun' },
    { word: 'radio', translation: 'радио', level: 2, category: 'noun' },
    { word: 'game', translation: 'игра', level: 2, category: 'noun' },
    { word: 'ball', translation: 'топка', level: 2, category: 'noun' },
    { word: 'toy', translation: 'играчка', level: 2, category: 'noun' },
    { word: 'kitchen', translation: 'кухня', level: 2, category: 'noun' },
    { word: 'bathroom', translation: 'баня', level: 2, category: 'noun' },
    { word: 'bedroom', translation: 'спалня', level: 2, category: 'noun' },
    { word: 'wall', translation: 'стена', level: 2, category: 'noun' },
    { word: 'floor', translation: 'под', level: 2, category: 'noun' },
    { word: 'ceiling', translation: 'таван', level: 2, category: 'noun' },
    { word: 'stairs', translation: 'стълби', level: 2, category: 'noun' },
    { word: 'clock', translation: 'часовник (стенен)', level: 2, category: 'noun' },
    { word: 'picture', translation: 'снимка', level: 2, category: 'noun' },
    { word: 'mirror', translation: 'огледало', level: 2, category: 'noun' },
    { word: 'lamp', translation: 'лампа', level: 2, category: 'noun' },
    { word: 'light', translation: 'светлина', level: 2, category: 'noun' },
    // VOCABULARY DATA - CHUNK 6 (Words 501-600)
// Copy and paste this into your vocabulary array

    { word: 'Monday', translation: 'понеделник', level: 2, category: 'noun' },
    { word: 'Tuesday', translation: 'вторник', level: 2, category: 'noun' },
    { word: 'Wednesday', translation: 'сряда', level: 2, category: 'noun' },
    { word: 'Thursday', translation: 'четвъртък', level: 2, category: 'noun' },
    { word: 'Friday', translation: 'петък', level: 2, category: 'noun' },
    { word: 'Saturday', translation: 'събота', level: 2, category: 'noun' },
    { word: 'Sunday', translation: 'неделя', level: 2, category: 'noun' },
    { word: 'January', translation: 'януари', level: 2, category: 'noun' },
    { word: 'February', translation: 'февруари', level: 2, category: 'noun' },
    { word: 'March', translation: 'март', level: 2, category: 'noun' },
    { word: 'April', translation: 'април', level: 2, category: 'noun' },
    { word: 'May', translation: 'май', level: 2, category: 'noun' },
    { word: 'June', translation: 'юни', level: 2, category: 'noun' },
    { word: 'July', translation: 'юли', level: 2, category: 'noun' },
    { word: 'August', translation: 'август', level: 2, category: 'noun' },
    { word: 'September', translation: 'септември', level: 2, category: 'noun' },
    { word: 'October', translation: 'октомври', level: 2, category: 'noun' },
    { word: 'November', translation: 'ноември', level: 2, category: 'noun' },
    { word: 'December', translation: 'декември', level: 2, category: 'noun' },
    { word: 'birthday', translation: 'рожден ден', level: 2, category: 'noun' },
    { word: 'holiday', translation: 'празник', level: 2, category: 'noun' },
    { word: 'party', translation: 'парти', level: 2, category: 'noun' },
    { word: 'gift', translation: 'подарък', level: 2, category: 'noun' },
    { word: 'flower', translation: 'цвете', level: 2, category: 'noun' },
    { word: 'grass', translation: 'трева', level: 2, category: 'noun' },
    { word: 'plant', translation: 'растение', level: 2, category: 'noun' },
    { word: 'horse', translation: 'кон', level: 2, category: 'noun' },
    { word: 'cow', translation: 'крава', level: 2, category: 'noun' },
    { word: 'pig', translation: 'прасе', level: 2, category: 'noun' },
    { word: 'sheep', translation: 'овца', level: 2, category: 'noun' },
    { word: 'chicken', translation: 'кокошка', level: 2, category: 'noun' },
    { word: 'duck', translation: 'патица', level: 2, category: 'noun' },
    { word: 'rabbit', translation: 'заек', level: 2, category: 'noun' },
    { word: 'mouse', translation: 'мишка', level: 2, category: 'noun' },
    { word: 'butterfly', translation: 'пеперуда', level: 2, category: 'noun' },
    { word: 'bee', translation: 'пчела', level: 2, category: 'noun' },
    { word: 'ant', translation: 'мравка', level: 2, category: 'noun' },
    { word: 'spider', translation: 'паяк', level: 2, category: 'noun' },
    { word: 'snake', translation: 'змия', level: 2, category: 'noun' },
    { word: 'lion', translation: 'лъв', level: 2, category: 'noun' },
    { word: 'tiger', translation: 'тигър', level: 2, category: 'noun' },
    { word: 'bear', translation: 'мечка', level: 2, category: 'noun' },
    { word: 'elephant', translation: 'слон', level: 2, category: 'noun' },
    { word: 'monkey', translation: 'маймуна', level: 2, category: 'noun' },
    { word: 'zoo', translation: 'зоологическа градина', level: 2, category: 'noun' },
    { word: 'tired', translation: 'уморен', level: 2, category: 'adjective' },
    { word: 'hungry', translation: 'гладен', level: 2, category: 'adjective' },
    { word: 'thirsty', translation: 'жаден', level: 2, category: 'adjective' },
    { word: 'sick', translation: 'болен', level: 2, category: 'adjective' },
    { word: 'healthy', translation: 'здрав', level: 2, category: 'adjective' },
    { word: 'busy', translation: 'зает', level: 2, category: 'adjective' },
    { word: 'free', translation: 'свободен', level: 2, category: 'adjective' },
    { word: 'ready', translation: 'готов', level: 2, category: 'adjective' },
    { word: 'careful', translation: 'внимателен', level: 2, category: 'adjective' },
    { word: 'safe', translation: 'безопасен', level: 2, category: 'adjective' },
    { word: 'dangerous', translation: 'опасен', level: 2, category: 'adjective' },
    { word: 'clean', translation: 'чист', level: 2, category: 'adjective' },
    { word: 'dirty', translation: 'мръсен', level: 2, category: 'adjective' },
    { word: 'wet', translation: 'мокър', level: 2, category: 'adjective' },
    { word: 'dry', translation: 'сух', level: 2, category: 'adjective' },
    { word: 'loud', translation: 'шумен', level: 2, category: 'adjective' },
    { word: 'quiet', translation: 'тих', level: 2, category: 'adjective' },
    { word: 'soft', translation: 'мек', level: 2, category: 'adjective' },
    { word: 'cheap', translation: 'евтин', level: 2, category: 'adjective' },
    { word: 'expensive', translation: 'скъп', level: 2, category: 'adjective' },
    { word: 'rich', translation: 'богат', level: 2, category: 'adjective' },
    { word: 'poor', translation: 'беден', level: 2, category: 'adjective' },
    { word: 'famous', translation: 'известен', level: 2, category: 'adjective' },
    { word: 'popular', translation: 'популярен', level: 2, category: 'adjective' },
    { word: 'favorite', translation: 'любим', level: 2, category: 'adjective' },
    { word: 'special', translation: 'специален', level: 2, category: 'adjective' },
    { word: 'strange', translation: 'странен', level: 2, category: 'adjective' },
    { word: 'funny', translation: 'смешен', level: 2, category: 'adjective' },
    { word: 'serious', translation: 'сериозен', level: 2, category: 'adjective' },
    { word: 'angry', translation: 'ядосан', level: 2, category: 'adjective' },
    { word: 'worried', translation: 'притеснен', level: 2, category: 'adjective' },
    { word: 'excited', translation: 'развълнуван', level: 2, category: 'adjective' },
    { word: 'surprised', translation: 'изненадан', level: 2, category: 'adjective' },
    { word: 'afraid', translation: 'уплашен', level: 2, category: 'adjective' },
    { word: 'brave', translation: 'смел', level: 2, category: 'adjective' },
    { word: 'smart', translation: 'умен', level: 2, category: 'adjective' },
    { word: 'stupid', translation: 'глупав', level: 2, category: 'adjective' },
    { word: 'kind', translation: 'добър', level: 2, category: 'adjective' },
    { word: 'mean', translation: 'зъл', level: 2, category: 'adjective' },
    { word: 'friendly', translation: 'приятелски', level: 2, category: 'adjective' },
    { word: 'polite', translation: 'учтив', level: 2, category: 'adjective' },
    { word: 'rude', translation: 'груб', level: 2, category: 'adjective' },
    { word: 'honest', translation: 'честен', level: 2, category: 'adjective' },
    { word: 'lucky', translation: 'късметлия', level: 2, category: 'adjective' },
    { word: 'unlucky', translation: 'нещастник', level: 2, category: 'adjective' },
    { word: 'together', translation: 'заедно', level: 2, category: 'adverb' },
    { word: 'alone', translation: 'сам', level: 2, category: 'adverb' },
    { word: 'again', translation: 'отново', level: 2, category: 'adverb' },
    { word: 'already', translation: 'вече', level: 2, category: 'adverb' },
    { word: 'still', translation: 'все още', level: 2, category: 'adverb' },
    { word: 'yet', translation: 'още', level: 2, category: 'adverb' },
    // VOCABULARY DATA - CHUNK 6 (Words 501-600)
// Copy and paste this into your vocabulary array

    { word: 'Monday', translation: 'понеделник', level: 2, category: 'noun' },
    { word: 'Tuesday', translation: 'вторник', level: 2, category: 'noun' },
    { word: 'Wednesday', translation: 'сряда', level: 2, category: 'noun' },
    { word: 'Thursday', translation: 'четвъртък', level: 2, category: 'noun' },
    { word: 'Friday', translation: 'петък', level: 2, category: 'noun' },
    { word: 'Saturday', translation: 'събота', level: 2, category: 'noun' },
    { word: 'Sunday', translation: 'неделя', level: 2, category: 'noun' },
    { word: 'January', translation: 'януари', level: 2, category: 'noun' },
    { word: 'February', translation: 'февруари', level: 2, category: 'noun' },
    { word: 'March', translation: 'март', level: 2, category: 'noun' },
    { word: 'April', translation: 'април', level: 2, category: 'noun' },
    { word: 'May', translation: 'май', level: 2, category: 'noun' },
    { word: 'June', translation: 'юни', level: 2, category: 'noun' },
    { word: 'July', translation: 'юли', level: 2, category: 'noun' },
    { word: 'August', translation: 'август', level: 2, category: 'noun' },
    { word: 'September', translation: 'септември', level: 2, category: 'noun' },
    { word: 'October', translation: 'октомври', level: 2, category: 'noun' },
    { word: 'November', translation: 'ноември', level: 2, category: 'noun' },
    { word: 'December', translation: 'декември', level: 2, category: 'noun' },
    { word: 'birthday', translation: 'рожден ден', level: 2, category: 'noun' },
    { word: 'holiday', translation: 'празник', level: 2, category: 'noun' },
    { word: 'party', translation: 'парти', level: 2, category: 'noun' },
    { word: 'gift', translation: 'подарък', level: 2, category: 'noun' },
    { word: 'flower', translation: 'цвете', level: 2, category: 'noun' },
    { word: 'grass', translation: 'трева', level: 2, category: 'noun' },
    { word: 'plant', translation: 'растение', level: 2, category: 'noun' },
    { word: 'horse', translation: 'кон', level: 2, category: 'noun' },
    { word: 'cow', translation: 'крава', level: 2, category: 'noun' },
    { word: 'pig', translation: 'прасе', level: 2, category: 'noun' },
    { word: 'sheep', translation: 'овца', level: 2, category: 'noun' },
    { word: 'chicken', translation: 'кокошка', level: 2, category: 'noun' },
    { word: 'duck', translation: 'патица', level: 2, category: 'noun' },
    { word: 'rabbit', translation: 'заек', level: 2, category: 'noun' },
    { word: 'mouse', translation: 'мишка', level: 2, category: 'noun' },
    { word: 'butterfly', translation: 'пеперуда', level: 2, category: 'noun' },
    { word: 'bee', translation: 'пчела', level: 2, category: 'noun' },
    { word: 'ant', translation: 'мравка', level: 2, category: 'noun' },
    { word: 'spider', translation: 'паяк', level: 2, category: 'noun' },
    { word: 'snake', translation: 'змия', level: 2, category: 'noun' },
    { word: 'lion', translation: 'лъв', level: 2, category: 'noun' },
    { word: 'tiger', translation: 'тигър', level: 2, category: 'noun' },
    { word: 'bear', translation: 'мечка', level: 2, category: 'noun' },
    { word: 'elephant', translation: 'слон', level: 2, category: 'noun' },
    { word: 'monkey', translation: 'маймуна', level: 2, category: 'noun' },
    { word: 'zoo', translation: 'зоологическа градина', level: 2, category: 'noun' },
    { word: 'tired', translation: 'уморен', level: 2, category: 'adjective' },
    { word: 'hungry', translation: 'гладен', level: 2, category: 'adjective' },
    { word: 'thirsty', translation: 'жаден', level: 2, category: 'adjective' },
    { word: 'sick', translation: 'болен', level: 2, category: 'adjective' },
    { word: 'healthy', translation: 'здрав', level: 2, category: 'adjective' },
    { word: 'busy', translation: 'зает', level: 2, category: 'adjective' },
    { word: 'free', translation: 'свободен', level: 2, category: 'adjective' },
    { word: 'ready', translation: 'готов', level: 2, category: 'adjective' },
    { word: 'careful', translation: 'внимателен', level: 2, category: 'adjective' },
    { word: 'safe', translation: 'безопасен', level: 2, category: 'adjective' },
    { word: 'dangerous', translation: 'опасен', level: 2, category: 'adjective' },
    { word: 'clean', translation: 'чист', level: 2, category: 'adjective' },
    { word: 'dirty', translation: 'мръсен', level: 2, category: 'adjective' },
    { word: 'wet', translation: 'мокър', level: 2, category: 'adjective' },
    { word: 'dry', translation: 'сух', level: 2, category: 'adjective' },
    { word: 'loud', translation: 'шумен', level: 2, category: 'adjective' },
    { word: 'quiet', translation: 'тих', level: 2, category: 'adjective' },
    { word: 'soft', translation: 'мек', level: 2, category: 'adjective' },
    { word: 'cheap', translation: 'евтин', level: 2, category: 'adjective' },
    { word: 'expensive', translation: 'скъп', level: 2, category: 'adjective' },
    { word: 'rich', translation: 'богат', level: 2, category: 'adjective' },
    { word: 'poor', translation: 'беден', level: 2, category: 'adjective' },
    { word: 'famous', translation: 'известен', level: 2, category: 'adjective' },
    { word: 'popular', translation: 'популярен', level: 2, category: 'adjective' },
    { word: 'favorite', translation: 'любим', level: 2, category: 'adjective' },
    { word: 'special', translation: 'специален', level: 2, category: 'adjective' },
    { word: 'strange', translation: 'странен', level: 2, category: 'adjective' },
    { word: 'funny', translation: 'смешен', level: 2, category: 'adjective' },
    { word: 'serious', translation: 'сериозен', level: 2, category: 'adjective' },
    { word: 'angry', translation: 'ядосан', level: 2, category: 'adjective' },
    { word: 'worried', translation: 'притеснен', level: 2, category: 'adjective' },
    { word: 'excited', translation: 'развълнуван', level: 2, category: 'adjective' },
    { word: 'surprised', translation: 'изненадан', level: 2, category: 'adjective' },
    { word: 'afraid', translation: 'уплашен', level: 2, category: 'adjective' },
    { word: 'brave', translation: 'смел', level: 2, category: 'adjective' },
    { word: 'smart', translation: 'умен', level: 2, category: 'adjective' },
    { word: 'stupid', translation: 'глупав', level: 2, category: 'adjective' },
    { word: 'kind', translation: 'добър', level: 2, category: 'adjective' },
    { word: 'mean', translation: 'зъл', level: 2, category: 'adjective' },
    { word: 'friendly', translation: 'приятелски', level: 2, category: 'adjective' },
    { word: 'polite', translation: 'учтив', level: 2, category: 'adjective' },
    { word: 'rude', translation: 'груб', level: 2, category: 'adjective' },
    { word: 'honest', translation: 'честен', level: 2, category: 'adjective' },
    { word: 'lucky', translation: 'късметлия', level: 2, category: 'adjective' },
    { word: 'unlucky', translation: 'нещастник', level: 2, category: 'adjective' },
    { word: 'together', translation: 'заедно', level: 2, category: 'adverb' },
    { word: 'alone', translation: 'сам', level: 2, category: 'adverb' },
    { word: 'again', translation: 'отново', level: 2, category: 'adverb' },
    { word: 'already', translation: 'вече', level: 2, category: 'adverb' },
    { word: 'still', translation: 'все още', level: 2, category: 'adverb' },
    { word: 'yet', translation: 'още', level: 2, category: 'adverb' },
    // VOCABULARY DATA - CHUNK 9 (Words 801-900)
// Copy and paste this into your vocabulary array

    { word: 'judge', translation: 'съдия', level: 3, category: 'noun' },
    { word: 'lawyer', translation: 'адвокат', level: 3, category: 'noun' },
    { word: 'crime', translation: 'престъпление', level: 3, category: 'noun' },
    { word: 'war', translation: 'война', level: 3, category: 'noun' },
    { word: 'peace', translation: 'мир', level: 3, category: 'noun' },
    { word: 'freedom', translation: 'свобода', level: 3, category: 'noun' },
    { word: 'right', translation: 'право', level: 3, category: 'noun' },
    { word: 'duty', translation: 'дълг', level: 3, category: 'noun' },
    { word: 'responsibility', translation: 'отговорност', level: 3, category: 'noun' },
    { word: 'society', translation: 'общество', level: 3, category: 'noun' },
    { word: 'community', translation: 'общност', level: 3, category: 'noun' },
    { word: 'culture', translation: 'култура', level: 3, category: 'noun' },
    { word: 'tradition', translation: 'традиция', level: 3, category: 'noun' },
    { word: 'custom', translation: 'обичай', level: 3, category: 'noun' },
    { word: 'religion', translation: 'религия', level: 3, category: 'noun' },
    { word: 'science', translation: 'наука', level: 3, category: 'noun' },
    { word: 'technology', translation: 'технология', level: 3, category: 'noun' },
    { word: 'invention', translation: 'изобретение', level: 3, category: 'noun' },
    { word: 'discovery', translation: 'откритие', level: 3, category: 'noun' },
    { word: 'research', translation: 'изследване', level: 3, category: 'noun' },
    { word: 'experiment', translation: 'експеримент', level: 3, category: 'noun' },
    { word: 'theory', translation: 'теория', level: 3, category: 'noun' },
    { word: 'truth', translation: 'истина', level: 3, category: 'noun' },
    { word: 'lie', translation: 'лъжа', level: 3, category: 'noun' },
    { word: 'mistake', translation: 'грешка', level: 3, category: 'noun' },
    { word: 'error', translation: 'грешка', level: 3, category: 'noun' },
    { word: 'accident', translation: 'злополука', level: 3, category: 'noun' },
    { word: 'danger', translation: 'опасност', level: 3, category: 'noun' },
    { word: 'risk', translation: 'риск', level: 3, category: 'noun' },
    { word: 'solution', translation: 'решение', level: 3, category: 'noun' },
    { word: 'difficulty', translation: 'трудност', level: 3, category: 'noun' },
    { word: 'challenge', translation: 'предизвикателство', level: 3, category: 'noun' },
    { word: 'opportunity', translation: 'възможност', level: 3, category: 'noun' },
    { word: 'chance', translation: 'шанс', level: 3, category: 'noun' },
    { word: 'luck', translation: 'късмет', level: 3, category: 'noun' },
    { word: 'fortune', translation: 'съдба', level: 3, category: 'noun' },
    { word: 'success', translation: 'успех', level: 3, category: 'noun' },
    { word: 'failure', translation: 'провал', level: 3, category: 'noun' },
    { word: 'victory', translation: 'победа', level: 3, category: 'noun' },
    { word: 'defeat', translation: 'поражение', level: 3, category: 'noun' },
    { word: 'competition', translation: 'състезание', level: 3, category: 'noun' },
    { word: 'prize', translation: 'награда', level: 3, category: 'noun' },
    { word: 'present', translation: 'подарък', level: 3, category: 'noun' },
    { word: 'lesson', translation: 'урок', level: 3, category: 'noun' },
    { word: 'class', translation: 'клас', level: 3, category: 'noun' },
    { word: 'subject', translation: 'предмет', level: 3, category: 'noun' },
    { word: 'homework', translation: 'домашна работа', level: 3, category: 'noun' },
    { word: 'exam', translation: 'изпит', level: 3, category: 'noun' },
    { word: 'test', translation: 'тест', level: 3, category: 'noun' },
    { word: 'grade', translation: 'оценка', level: 3, category: 'noun' },
    { word: 'university', translation: 'университет', level: 3, category: 'noun' },
    { word: 'college', translation: 'колеж', level: 3, category: 'noun' },
    { word: 'degree', translation: 'степен', level: 3, category: 'noun' },
    { word: 'certificate', translation: 'сертификат', level: 3, category: 'noun' },
    { word: 'skill', translation: 'умение', level: 3, category: 'noun' },
    { word: 'ability', translation: 'способност', level: 3, category: 'noun' },
    { word: 'talent', translation: 'талант', level: 3, category: 'noun' },
    { word: 'knowledge', translation: 'знание', level: 3, category: 'noun' },
    { word: 'experience', translation: 'опит', level: 3, category: 'noun' },
    { word: 'practice', translation: 'практика', level: 3, category: 'noun' },
    { word: 'training', translation: 'обучение', level: 3, category: 'noun' },
    { word: 'language', translation: 'език', level: 3, category: 'noun' },
    { word: 'accent', translation: 'акцент', level: 3, category: 'noun' },
    { word: 'pronunciation', translation: 'произношение', level: 3, category: 'noun' },
    { word: 'grammar', translation: 'граматика', level: 3, category: 'noun' },
    { word: 'vocabulary', translation: 'речник', level: 3, category: 'noun' },
    { word: 'sentence', translation: 'изречение', level: 3, category: 'noun' },
    { word: 'paragraph', translation: 'параграф', level: 3, category: 'noun' },
    { word: 'article', translation: 'статия', level: 3, category: 'noun' },
    { word: 'chapter', translation: 'глава', level: 3, category: 'noun' },
    { word: 'page', translation: 'страница', level: 3, category: 'noun' },
    { word: 'line', translation: 'ред', level: 3, category: 'noun' },
    { word: 'title', translation: 'заглавие', level: 3, category: 'noun' },
    { word: 'author', translation: 'автор', level: 3, category: 'noun' },
    { word: 'writer', translation: 'писател', level: 3, category: 'noun' },
    { word: 'reader', translation: 'читател', level: 3, category: 'noun' },
    { word: 'character', translation: 'герой', level: 3, category: 'noun' },
    { word: 'plot', translation: 'сюжет', level: 3, category: 'noun' },
    { word: 'setting', translation: 'място на действие', level: 3, category: 'noun' },
    { word: 'theme', translation: 'тема', level: 3, category: 'noun' },
    { word: 'moral', translation: 'морал', level: 3, category: 'noun' },
    { word: 'message', translation: 'послание', level: 3, category: 'noun' },
    { word: 'significant', translation: 'значителен', level: 4, category: 'adjective' },
    { word: 'essential', translation: 'съществен', level: 4, category: 'adjective' },
    { word: 'fundamental', translation: 'основен', level: 4, category: 'adjective' },
    { word: 'crucial', translation: 'решаващ', level: 4, category: 'adjective' },
    { word: 'vital', translation: 'жизненоважен', level: 4, category: 'adjective' },
    { word: 'critical', translation: 'критичен', level: 4, category: 'adjective' },
    { word: 'substantial', translation: 'съществен', level: 4, category: 'adjective' },
    { word: 'considerable', translation: 'значителен', level: 4, category: 'adjective' },
    { word: 'enormous', translation: 'огромен', level: 4, category: 'adjective' },
    { word: 'tremendous', translation: 'огромен', level: 4, category: 'adjective' },
    { word: 'massive', translation: 'масивен', level: 4, category: 'adjective' },
    { word: 'tiny', translation: 'миниатюрен', level: 4, category: 'adjective' },
    { word: 'vast', translation: 'обширен', level: 4, category: 'adjective' },
    { word: 'extensive', translation: 'обширен', level: 4, category: 'adjective' },
    // VOCABULARY DATA - CHUNK 10 (Words 901-1000) - FINAL CHUNK!
// Copy and paste this into your vocabulary array

    { word: 'comprehensive', translation: 'изчерпателен', level: 4, category: 'adjective' },
    { word: 'complex', translation: 'сложен', level: 4, category: 'adjective' },
    { word: 'sophisticated', translation: 'изискан', level: 4, category: 'adjective' },
    { word: 'elaborate', translation: 'детайлен', level: 4, category: 'adjective' },
    { word: 'precise', translation: 'точен', level: 4, category: 'adjective' },
    { word: 'accurate', translation: 'прецизен', level: 4, category: 'adjective' },
    { word: 'exact', translation: 'точен', level: 4, category: 'adjective' },
    { word: 'specific', translation: 'специфичен', level: 4, category: 'adjective' },
    { word: 'particular', translation: 'конкретен', level: 4, category: 'adjective' },
    { word: 'individual', translation: 'индивидуален', level: 4, category: 'adjective' },
    { word: 'unique', translation: 'уникален', level: 4, category: 'adjective' },
    { word: 'unusual', translation: 'необичаен', level: 4, category: 'adjective' },
    { word: 'extraordinary', translation: 'извънреден', level: 4, category: 'adjective' },
    { word: 'remarkable', translation: 'забележителен', level: 4, category: 'adjective' },
    { word: 'outstanding', translation: 'изключителен', level: 4, category: 'adjective' },
    { word: 'superior', translation: 'превъзходен', level: 4, category: 'adjective' },
    { word: 'inferior', translation: 'по-долен', level: 4, category: 'adjective' },
    { word: 'adequate', translation: 'адекватен', level: 4, category: 'adjective' },
    { word: 'insufficient', translation: 'недостатъчен', level: 4, category: 'adjective' },
    { word: 'excessive', translation: 'прекомерен', level: 4, category: 'adjective' },
    { word: 'moderate', translation: 'умерен', level: 4, category: 'adjective' },
    { word: 'extreme', translation: 'екстремен', level: 4, category: 'adjective' },
    { word: 'intense', translation: 'интензивен', level: 4, category: 'adjective' },
    { word: 'severe', translation: 'сериозен', level: 4, category: 'adjective' },
    { word: 'harsh', translation: 'суров', level: 4, category: 'adjective' },
    { word: 'mild', translation: 'мек', level: 4, category: 'adjective' },
    { word: 'gentle', translation: 'нежен', level: 4, category: 'adjective' },
    { word: 'delicate', translation: 'деликатен', level: 4, category: 'adjective' },
    { word: 'fragile', translation: 'чуплив', level: 4, category: 'adjective' },
    { word: 'robust', translation: 'здрав', level: 4, category: 'adjective' },
    { word: 'sturdy', translation: 'як', level: 4, category: 'adjective' },
    { word: 'durable', translation: 'траен', level: 4, category: 'adjective' },
    { word: 'permanent', translation: 'постоянен', level: 4, category: 'adjective' },
    { word: 'temporary', translation: 'временен', level: 4, category: 'adjective' },
    { word: 'stable', translation: 'стабилен', level: 4, category: 'adjective' },
    { word: 'constant', translation: 'постоянен', level: 4, category: 'adjective' },
    { word: 'variable', translation: 'променлив', level: 4, category: 'adjective' },
    { word: 'flexible', translation: 'гъвкав', level: 4, category: 'adjective' },
    { word: 'rigid', translation: 'твърд', level: 4, category: 'adjective' },
    { word: 'firm', translation: 'твърд', level: 4, category: 'adjective' },
    { word: 'solid', translation: 'солиден', level: 4, category: 'adjective' },
    { word: 'liquid', translation: 'течен', level: 4, category: 'adjective' },
    { word: 'transparent', translation: 'прозрачен', level: 4, category: 'adjective' },
    { word: 'opaque', translation: 'непрозрачен', level: 4, category: 'adjective' },
    { word: 'visible', translation: 'видим', level: 4, category: 'adjective' },
    { word: 'invisible', translation: 'невидим', level: 4, category: 'adjective' },
    { word: 'obvious', translation: 'очевиден', level: 4, category: 'adjective' },
    { word: 'apparent', translation: 'явен', level: 4, category: 'adjective' },
    { word: 'evident', translation: 'ясен', level: 4, category: 'adjective' },
    { word: 'clear', translation: 'ясен', level: 4, category: 'adjective' },
    { word: 'vague', translation: 'неясен', level: 4, category: 'adjective' },
    { word: 'ambiguous', translation: 'двусмислен', level: 4, category: 'adjective' },
    { word: 'explicit', translation: 'ясен', level: 4, category: 'adjective' },
    { word: 'implicit', translation: 'подразбиращ се', level: 4, category: 'adjective' },
    { word: 'conscious', translation: 'съзнателен', level: 4, category: 'adjective' },
    { word: 'unconscious', translation: 'несъзнателен', level: 4, category: 'adjective' },
    { word: 'aware', translation: 'наясно', level: 4, category: 'adjective' },
    { word: 'unaware', translation: 'неосведомен', level: 4, category: 'adjective' },
    { word: 'ignorant', translation: 'незнаещ', level: 4, category: 'adjective' },
    { word: 'knowledgeable', translation: 'знаещ', level: 4, category: 'adjective' },
    { word: 'intelligent', translation: 'интелигентен', level: 4, category: 'adjective' },
    { word: 'wise', translation: 'мъдър', level: 4, category: 'adjective' },
    { word: 'foolish', translation: 'глупав', level: 4, category: 'adjective' },
    { word: 'clever', translation: 'умен', level: 4, category: 'adjective' },
    { word: 'brilliant', translation: 'блестящ', level: 4, category: 'adjective' },
    { word: 'talented', translation: 'талантлив', level: 4, category: 'adjective' },
    { word: 'skilled', translation: 'умел', level: 4, category: 'adjective' },
    { word: 'capable', translation: 'способен', level: 4, category: 'adjective' },
    { word: 'competent', translation: 'компетентен', level: 4, category: 'adjective' },
    { word: 'efficient', translation: 'ефективен', level: 4, category: 'adjective' },
    { word: 'effective', translation: 'ефикасен', level: 4, category: 'adjective' },
    { word: 'productive', translation: 'продуктивен', level: 4, category: 'adjective' },
    { word: 'creative', translation: 'творчески', level: 4, category: 'adjective' },
    { word: 'innovative', translation: 'иновативен', level: 4, category: 'adjective' },
    { word: 'original', translation: 'оригинален', level: 4, category: 'adjective' },
    { word: 'authentic', translation: 'автентичен', level: 4, category: 'adjective' },
    { word: 'genuine', translation: 'истински', level: 4, category: 'adjective' },
    { word: 'artificial', translation: 'изкуствен', level: 4, category: 'adjective' },
    { word: 'synthetic', translation: 'синтетичен', level: 4, category: 'adjective' },
    { word: 'accommodate', translation: 'настанявам', level: 4, category: 'verb' },
    { word: 'accomplish', translation: 'постигам', level: 4, category: 'verb' },
    { word: 'achieve', translation: 'постигам', level: 4, category: 'verb' },
    { word: 'acquire', translation: 'придобивам', level: 4, category: 'verb' },
    { word: 'adapt', translation: 'адаптирам', level: 4, category: 'verb' },
    { word: 'adjust', translation: 'нагласявам', level: 4, category: 'verb' },
    { word: 'administer', translation: 'администрирам', level: 4, category: 'verb' },
    { word: 'advocate', translation: 'застъпвам', level: 4, category: 'verb' },
    { word: 'allocate', translation: 'разпределям', level: 4, category: 'verb' },
    { word: 'anticipate', translation: 'предвиждам', level: 4, category: 'verb' },
    { word: 'appreciate', translation: 'оценявам', level: 4, category: 'verb' },
    { word: 'approach', translation: 'приближавам', level: 4, category: 'verb' },
    { word: 'assess', translation: 'оценявам', level: 4, category: 'verb' },
    { word: 'assume', translation: 'предполагам', level: 4, category: 'verb' },
    { word: 'assure', translation: 'уверявам', level: 4, category: 'verb' },
    { word: 'attribute', translation: 'приписвам', level: 4, category: 'verb' },
    { word: 'characterize', translation: 'характеризирам', level: 4, category: 'verb' },
    { word: 'clarify', translation: 'изяснявам', level: 4, category: 'verb' },
    { word: 'collaborate', translation: 'сътрудничa', level: 4, category: 'verb' },
    { word: 'compensate', translation: 'компенсирам', level: 4, category: 'verb' },
]

export default vocabulary;